# Generated by Django 2.1 on 2018-08-19 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_auto_20180819_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name - പേര്')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], verbose_name='Gender - ലിംഗം')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Age - വയസ് ')),
                ('relation', models.CharField(choices=[('FA', 'Father - അച്ഛൻ'), ('MA', 'Mother - അമ്മ'), ('SO', 'Son - മകൻ'), ('DA', 'Daughter - മകൾ'), ('BR', 'Brother - സഹോദരൻ'), ('ST', 'Sister - സഹോദരി '), ('WF', 'Wife - ഭാര്യ '), ('GF', 'Grand Father - മുത്തച്ഛൻ'), ('GM', 'Grand Mother - മുത്തശ്ശി'), ('GS', 'Grand Son - കൊച്ചുമകൻ '), ('GD', 'Grand Daughter - കൊച്ചുമകൾ ')], max_length=3, verbose_name='Relation - ബന്ധം')),
                ('uniqueid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Adhaar/Ration Card/Voters Id (Any one)- ആധാർ / റേഷൻകാർഡ് / വോട്ടർ ഐഡി  (ഏതങ്കിലും ഒന്ന് )')),
                ('staus', models.CharField(choices=[('S', 'Safe'), ('M', 'Missing'), ('D', 'Died')], max_length=1)),
            ],
            options={
                'verbose_name': 'Family: Member',
                'verbose_name_plural': 'Family: Members',
            },
        ),
        migrations.CreateModel(
            name='SurvivedFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15, verbose_name='Districts - ജില്ല')),
                ('taluk', models.CharField(max_length=100, verbose_name='Taluk - താലൂക്ക്')),
                ('village', models.CharField(max_length=100, verbose_name='Village - വില്ലേജ്')),
                ('place', models.CharField(max_length=100, verbose_name='Your Native Place in Village  - വില്ലേജിൽ നിങ്ങളുടെ താമസസ്ഥലം')),
                ('name', models.CharField(max_length=100, verbose_name='Name - പേര്')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], verbose_name='Gender - ലിംഗം')),
                ('age', models.IntegerField(verbose_name='Age - വയസ് ')),
                ('uniqueid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Adhaar/Ration Card/Voters Id (Any one)- ആധാർ / റേഷൻകാർഡ് / വോട്ടർ ഐഡി  (ഏതങ്കിലും ഒന്ന് )')),
                ('housename', models.CharField(max_length=100, verbose_name='House Name  - വീട്ടുപേര് ')),
                ('pin', models.IntegerField(verbose_name='Pincode - പിൻകോഡ് ')),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Mobile - മൊബൈൽ')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Address - വിലാസം ')),
                ('current_place', models.CharField(max_length=100, verbose_name='Now Staying at - ഇപ്പോൾ  താമസിക്കുന്ന സ്ഥലം')),
                ('updated_by', models.CharField(choices=[('S', 'self'), ('V', 'volunteer')], max_length=100, verbose_name='Updated By  - അപ്ഡേറ്റ്  ചെയുന്ന ആൾ ')),
            ],
            options={
                'verbose_name': 'Survived: Family',
                'verbose_name_plural': 'Survived: Families',
            },
        ),
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.SurvivedFamily'),
        ),
    ]
