# Generated by Django 2.1 on 2018-08-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_add_status_to_relief_camp'),
        ('mainapp', '0057_auto_20180819_1712'),
    ]

    operations = [
    ]
